### ISSUE TITLE
Current state of this library 

### ISSUE THREAD

**Issue by andre2007** [rumbu13/decimal#7]
This library looks really great!

Is this library ready to be uses in production or what is missing?

The last release mentioned some failing unittests. Ate these issues solved in the meantime?

**Comment by rumbu13** [comment]
There are some corner cases for trigonometry functions where I am not happy with the results. Unfortunately, I don't have the time, nor the experience (math) to analyze further. If someone will encounter such corner case, I will look into it. 

Otherwise, the rest of operators/functions are working perfectly.
